name: CI

on:
  pull_request:
    branches:
      - develop
      - main
  push:
    branches:
      - develop

permissions:
  contents: read
  packages: write

jobs:
  ci:
    name: Validación básica
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Comprobar estructura
        run: |
          test -f README.md
          test -d .github/workflows

      - name: Validar archivos Markdown
        run: |
          find . -name "*.md" -type f -print

      - name: Iniciar sesión en GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build y publicar imagen Docker
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/raulgutierrezp/devops-sre-lab:latest
            ghcr.io/raulgutierrezp/devops-sre-lab:${{ github.sha }}